# Build stage
FROM microsoft/aspnetcore-build:2 AS build

# set working directory
WORKDIR /app

# Restore
COPY run/run.csproj ./run/
RUN dotnet restore run/run.csproj
COPY src/src.csproj ./src/
RUN dotnet restore src/src.csproj
COPY test/test.csproj ./test/
RUN dotnet restore test/test.csproj

# Copy src
COPY . .

# Test
ENV TEAMCITY_PROJECT_NAME=fake
#RUN dotnet test test/test.csproj
